### ISSUE TITLE
Add a new entry in vault_trusted_domains

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#3]
Hi there,
I suggest you to consider adding a new entry in the section related to _vault_trusted_domains_ in your `provision_vault.yml`, as follows:

```
vault_trusted_domains:
  - '^stage\.{{vault_site_domain}}\.{{vault_company_name}}\.com$'
  - '^.+\.{{vault_site_domain}}\.{{vault_company_name}}\.com$'
  - '^{{vault_site_domain}}\.{{vault_company_name}}\.com$'
  ```

**Comment by webfer** [comment]
>Thank you so much for your contributions.
Have a nice day!
