### ISSUE TITLE
Ensure settings.live.php are properly set!

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#32]
Hi there,
The settings.php & settings.live.php file must have permissions set to 600. (rw--).

I recommend to run this command globally , for all the folders and files of the site in a Ansible task.
`find . -type f -exec chmod u=rw,g=r,o=r '{}' \; && find . -type d -exec chmod u=rwx,g=rx,o=rx '{}' \;`

And, at last but not least, set the permissions for the settings' files as explained above.

This is the most important thing! ;-)

**Comment by webfer** [comment]
Thank you for your suggestion!
