### ISSUE TITLE
Add shorthands for ansible-deploy parameters

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#38]
Hi there!

It would be nice if additionally we had some shorthands for `ansible-deploy` parameters, don't  you?
I suggest the following ones:

- `--stage`, `-s`
- `--live`, `-l`
- `--install`, `-i`
- `--update`, `-u`

Thank you in advance,

**Comment by webfer** [comment]
@donbuche  Thank you for your suggestions.
Done!
Please, download your installer to enjoy the new feature.
