### ISSUE TITLE
Add drush locale-check and drush locale-update tasks

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#47]
Hi there!

Could you add new `drush locale-check` and `drush locale-update` related tasks just before the "_Rebuild Drupal cache using Drush_" task, in `after-symlink.yml` file?

Friendly reminder: A `drush cr` related task is needed after these two new tasks are triggered, in order to get them working properly ;-)

**Comment by webfer** [comment]
@donbuche 
Thank you so much for your kindly contribution.
