### ISSUE TITLE
Modify 

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#58]
Remove those from settings.live.php and let each developer set the values in their own settings.php file:

- $config_directories['sync'] = '../config/sync';
- $settings['hash_salt'] = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
- $settings['trusted_host_patterns'] (entirely)
- $settings['config_sync_directory'] = '../config/sync';

**Comment by webfer** [comment]
@donbuche Thank you for your suggestion. It's done!
